sudo: true
language: haxe

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/02e5112c59e387a9d167
      - https://webhooks.gitter.im/e/2cf2b3fce38bfb758c65
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

os:
  - linux

haxe:
  - "3.2.1"
  - development

before_install:
    - git clone https://github.com/haxeui/haxeui-core.git --depth=1
    - haxelib dev haxeui-core haxeui-core

    # We need a git version of hxcpp for now
    - git clone https://github.com/HaxeFoundation/hxcpp.git --depth=1
    - haxelib dev hxcpp hxcpp
    - cd hxcpp/tools/hxcpp
    - haxe compile.hxml
    - cd ../build
    - haxe compile.hxml
    - cd ../../project
    - neko build.n clean
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        neko build.n linux-64;
        elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        neko build.n;
        fi
    - cd ../../..

install:
    # - haxelib install hxcpp
    - haxelib install nme
    - haxelib run nme setup -y
    - haxelib install hscript
    # - haxelib dev haxeui-openfl $TRAVIS_BUILD_DIR

script:
    - cd $TRAVIS_BUILD_DIR
    - haxe linux.hxml